"""Trading system core package."""

from ..timeframes import Timeframe, validate_timeframe
from .interfaces import (
    AnalyzerContext,
    FactorScore,
    JsonDict,
    OptimizationStats,
    PositionPlan,
    SignalExplanation,
    TradingAnalyzer,
    TradingSignalPayload,
    deserialize_signal_payload,
    parse_collector_payload,
    serialize_signal_payload,
)
from .volume_orderbook_analyzer import (
    analyze_volume_orderbook,
    calculate_mm_confidence_weighted,
    calculate_order_imbalance,
    analyze_smart_money_activity,
    detect_liquidity_zones,
)
from .technical_analysis import (
    analyze_technical_factors,
    analyze_macd,
    analyze_rsi,
    analyze_atr,
    analyze_bollinger_bands,
    detect_divergences,
)
from .sentiment_analyzer import (
    analyze_sentiment_factors,
    create_sentiment_factor_score,
)
from .multitimeframe_analyzer import (
    analyze_multitimeframe_factors,
    create_multitimeframe_factor_score,
)
from .signal_generator import (
    SignalConfig,
    SignalFactors,
    generate_trading_signal,
)
from .position_manager import (
    PositionManagerConfig,
    DiversificationGuard,
    PositionSizingResult,
    PositionManagerResult,
    calculate_risk_based_position_size,
    assess_market_conditions,
    estimate_holding_horizon,
    create_position_plan,
    create_diversification_guard,
    validate_tp_sl_spacing,
)
from .statistics_optimizer import (
    SignalOutcome,
    PerformanceKPIs,
    WeightAdjustment,
    OptimizationResult,
    StatsOptimizerConfig,
    StatisticsOptimizer,
    create_stats_optimizer,
    create_synthetic_outcomes,
)
from .trading_system import (
    MacroBlackoutConfig,
    TradingConfig,
    TradingState,
    TradingOrchestrator,
    MacroBlackoutFilter,
    create_trading_orchestrator,
    create_default_config,
)
from .backtester import (
    BacktestConfig,
    ParameterSet,
    BacktestResult,
    AdaptiveWeightResult,
    Backtester,
    indicator_defaults_for,
)
from .backtest_data_builder import (
    BacktestPayload,
    build_backtest_payloads_from_candles,
)
from .data_sources import (
    HistoricalDataSource,
    BinanceKlinesSource,
    normalize_timestamp,
    validate_timestamps_monotonic,
    validate_no_future_timestamps,
)
from .adaptive_weights import (
    AdaptiveWeightConfig,
    WeightPerformance,
    AdaptationReport,
    AdaptiveWeightManager,
)

from .payload_loader import (
    PayloadProcessor,
    load_full_payload,
    load_and_process_payload_dict,
    validate_and_normalize_payload,
    extract_trading_context,
    payload_processor,
)
from .generate_signals import (
    generate_signals,
    generate_signals_from_payload,
)
from .signal_schema import (
    TradingSignalSchema,
    validate_signal_json,
    is_valid_signal_structure,
)

__all__ = [
    "Timeframe",
    "validate_timeframe",
    "AnalyzerContext",
    "FactorScore",
    "JsonDict",
    "OptimizationStats",
    "PositionPlan",
    "SignalExplanation",
    "SignalConfig",
    "SignalFactors",
    "PositionManagerConfig",
    "DiversificationGuard",
    "PositionSizingResult",
    "PositionManagerResult",
    "TradingAnalyzer",
    "TradingSignalPayload",
    "SignalOutcome",
    "PerformanceKPIs",
    "WeightAdjustment",
    "OptimizationResult",
    "StatsOptimizerConfig",
    "StatisticsOptimizer",
    "MacroBlackoutConfig",
    "TradingConfig",
    "TradingState",
    "TradingOrchestrator",
    "MacroBlackoutFilter",
    "BacktestConfig",
    "ParameterSet",
    "BacktestResult",
    "AdaptiveWeightResult",
    "Backtester",
    "BacktestPayload",
    "build_backtest_payloads_from_candles",
    "indicator_defaults_for",
    "HistoricalDataSource",
    "BinanceKlinesSource",
    "normalize_timestamp",
    "validate_timestamps_monotonic",

    "AdaptiveWeightConfig",
    "WeightPerformance",
    "AdaptationReport",
    "AdaptiveWeightManager",
    "PayloadProcessor",
    "load_full_payload",
    "load_and_process_payload_dict",
    "validate_and_normalize_payload",
    "extract_trading_context",
    "payload_processor",
    "deserialize_signal_payload",
    "parse_collector_payload",
    "serialize_signal_payload",
    "analyze_volume_orderbook",
    "calculate_mm_confidence_weighted",
    "calculate_order_imbalance",
    "analyze_smart_money_activity",
    "detect_liquidity_zones",
    "analyze_technical_factors",
    "analyze_macd",
    "analyze_rsi",
    "analyze_atr",
    "analyze_bollinger_bands",
    "detect_divergences",
    "analyze_sentiment_factors",
    "create_sentiment_factor_score",
    "analyze_multitimeframe_factors",
    "create_multitimeframe_factor_score",
    "generate_trading_signal",
    "calculate_risk_based_position_size",
    "assess_market_conditions",
    "estimate_holding_horizon",
    "create_position_plan",
    "create_diversification_guard",
    "validate_tp_sl_spacing",
    "create_stats_optimizer",
    "create_synthetic_outcomes",
    "create_trading_orchestrator",
    "create_default_config",
    "generate_signals",
    "generate_signals_from_payload",
    "TradingSignalSchema",
    "validate_signal_json",
    "is_valid_signal_structure",
]
