"""Indicator metrics collection toolkit for TradingView PineScript indicators."""

from .cli import main
from .trading_system import (
    AnalyzerContext,
    Backtester,
    BinanceKlinesSource,
    FactorScore,
    JsonDict,
    OptimizationStats,
    ParameterSet,
    PositionPlan,
    SignalExplanation,
    Timeframe,
    TradingAnalyzer,
    TradingSignalPayload,
    deserialize_signal_payload,
    generate_signals,
    indicator_defaults_for,
    load_full_payload,
    parse_collector_payload,
    serialize_signal_payload,
)

__all__ = [
    "main",
    "AnalyzerContext",
    "Backtester",
    "BinanceKlinesSource",
    "FactorScore",
    "JsonDict",
    "OptimizationStats",
    "ParameterSet",
    "PositionPlan",
    "SignalExplanation",
    "Timeframe",
    "TradingAnalyzer",
    "TradingSignalPayload",
    "deserialize_signal_payload",
    "generate_signals",
    "indicator_defaults_for",
    "load_full_payload",
    "parse_collector_payload",
    "serialize_signal_payload",
]
